# -*- coding: utf-8 -*-

from odoo import models, fields


class ProductTemplateCustom(models.Model):
    _inherit = 'product.template'
    _description = 'Clase para modificar el modulo de productos templates'

    unit_of_measure = fields.Selection([
        ('1', 'Barril'),
        ('2', 'Bolsa'),
        ('3', 'Bote'),
        ('4', 'Bultos'),
        ('5', 'Botella'),
        ('6', 'Caja/Cajón'),
        ('7', 'Cajetilla'),
        ('8', 'Centímetro'),
        ('9', 'Cilindro'),
        ('10', 'Conjunto'),
        ('11', 'Contenedor'),
        ('12', 'Día'),
        ('13', 'Docena'),
        ('14', 'Fardo'),
        ('15', 'Galones'),
        ('16', 'Grado'),
        ('17', 'Gramo'),
        ('18', 'Granel'),
        ('19', 'Hora'),
        ('20', 'Huacal'),
        ('21', 'Kilogramo'),
        ('22', 'Kilovatio Hora'),
        ('23', 'Libra'),
        ('24', 'Litro'),
        ('25', 'Lote'),
        ('26', 'Metro'),
        ('27', 'Metro Cuadrado'),
        ('28', 'Metro Cúbico'),
        ('29', 'Millones de Unidades Térmicas'),
        ('30', 'Minuto'),
        ('31', 'Paquete'),
        ('32', 'Par'),
        ('33', 'Pie'),
        ('34', 'Pieza'),
        ('35', 'Rollo'),
        ('36', 'Sobre'),
        ('37', 'Segundo'),
        ('38', 'Tanque'),
        ('39', 'Tonelada'),
        ('40', 'Tubo'),
        ('41', 'Yarda'),
        ('42', 'Yarda cuadrada'),
        ('43', 'Unidad'),
        ('44', 'Elemento'),
        ('45', 'Millar'),
        ('46', 'Saco'),
        ('47', 'Lata'),
        ('48', 'Display'),
        ('49', 'Bidón'),
        ('50', 'Ración'),
        ('51', 'Quintal'),
        ('52', 'Gross Register Tonnage (Toneladas de registro bruto)'),
        ('53', 'Pie cuadrado'),
        ('54', 'Pasajero'),
        ('55', 'Pulgadas'),
        ('56', 'Parqueo barcos en muelle'),
        ('57', 'Bandeja'),
        ('58', 'Hectárea'),
        ('59', 'Mililitro'),
        ('60', 'Miligramo'),
        ('61', 'Onzas'),
        ('62', 'Onzas Troy')
    ], default='1', string='Unidad de Medida')
